### PR TITLE
Fix for #203 batteryVoltage() returns zero

### PR DESCRIPTION
**Pull request by jimwhitelaw**
Fix batteryVoltage = 0. 

Payload is char array ending in V (ie, "12.5V") causing srttod to return zero. Fix removes the last char from payload so it converts properly.

### CODE REVIEW

**Review by jimwhitelaw — COMMENTED** [review]
WTH am I doing wrong that every PR includes a whack of old commits!? This fix was only one commit and one new example program file.

**Comment by PowerBroker2** [comment]
Idk, maybe delete your branch and refork? I'll merge this for now and hopefully it won't break my last update.

**Comment by themelisx** [comment]
@PowerBroker2  In which version this will be available to platformio ?

**Comment by PowerBroker2** [comment]
I don't know how platformio or it's library manager works, so I'm not sure. If it mirrors the Arduino IDE's library manager, it will be available in the next tagged release. For now, you can use the main branch as it has these updates already.

**Comment by themelisx** [comment]
When you are coding in VS Code and you are using platformio, you just add the follow lines into the platformio.ini file and it just works. So I cannot use the main branch. anyway, thank you for your answer 
lib_deps =
  powerbroker2/ELMDuino

**Comment by jimwhitelaw** [comment]
I use platformio - you can work with any branch/version/commit of a library in a couple of ways:

1. Specify the branch/commit/tag with #branch after the repo.  Ie, lib_deps =
https://github.com/powerbroker2/ELMDuino#master

2. Clone the branch you want locally and then provide a full path to your local repo in your lib_deps. It doesn’t need to be a remote repo. lib_deps =
/Users/jim/Documents/Platformio/Projects/ELMduino/src

First method is easiest if you just want to track a remote branch and use PIO tools to keep it up to date. Second method is easier if you want to be working on the lib itself.

**Comment by themelisx** [comment]
Good to know that.
Maybe it's a good idea to add this info to the readme file

**Comment by themelisx** [comment]
@jimwhitelaw I have tested your fix, indeed the "V" removed from your payload but the function still returns zero

**Comment by jimwhitelaw** [comment]
Can you please provide a sample of the code you are using and the debug (serial) output that is produced? Hx

**Comment by themelisx** [comment]
@jimwhitelaw I am using the same code as described on the description when I open the ticket.
Below is a part of my first comment.
Ok, now the payload does not contains the "V" character but the library still returns always zero,

int newValue = int(obd->batteryVoltage() * 10);
so I am wating to get 131

Query ODB value
Clearing input serial buffer
Sending the following command/query: AT RV
Received char: A
Received char: T
Received char: _
Received char: R
Received char: V
Received char: \r
Received char: 1
Received char: 3
Received char: .
Received char: 1
Received char: V
Received char: \r
Received char: \r
Received char: >
Delimiter found.
All chars received: ATRV13.1V

**Comment by themelisx** [comment]
@jimwhitelaw I added some lines (take a look to the end of this post).
Seems that the strtod fails even if the "V" has removed

Sending the following command/query: AT RV
        Received char: A
        Received char: T
        Received char: _
        Received char: R
        Received char: V
        Received char: \r
        Received char: 1
        Received char: 1
        Received char: .
        Received char: 8
        Received char: V
        Received char: \r
        Received char: \r
        Received char: >
Delimiter found.
All chars received: ATRV11.8V
Voltage:
0.00



            nb_query_state = SEND_COMMAND;       // Reset the query state machine for next command
            payload[strlen(payload) - 1] = '\0'; // remove the last char ("V") from the payload value
            float test = (float)strtod(payload, NULL);
            Serial.println("Voltage:");
            Serial.println(test);
            return (float)strtod(payload, NULL);

**Comment by jimwhitelaw** [comment]
OK, I have found the issue and implemented a fix. I will do some additional testing with a couple ELM327 devices before I submit a PR with the change. Stay tuned...

**Comment by jimwhitelaw** [comment]
After some investigation, I found that some ELM327 devices respond to the voltage command differently than others. I have submitted a PR (#217) that handles both scenarios. 

Also, I should note that the code you have provided may not do what you expect, even when batteryVoltage() is working properly. When the voltage value (a float) is multiplied by int value 10, the result is a float, but it only includes the integer portion of the original value. So the following code, given a voltage value of 13.1V:

```C
int newValue = int(obd->batteryVoltage() * 10);
``` 
Will return 130, not 131. You could probably mitigate this with the following:

```C
int newValue = (int)(obd->batteryVoltage() * 10.0)
```

**Pull request merged**
