### PR TITLE
Non-blocking update: Fix a few typos, add VIN query, update examples, update README

### PR DESCRIPTION
**Pull request by patfelst**
Hi @PowerBroker2 I've done more testing of some regular PIDs (absBaroPressure, engineCoolantTemp, oilTemp, manifoldPressure,  rpm). All working ok.

To test multiline response are still working ok (i.e. the responses with lines beginning with "n:" I added a function to query the Vehicle Identification Number (VIN - returns 49 chars over 3 lines). Note the library begin needs to be started with more than the default payload length, I used payloadLen = 60. The decoding of this had me scratching my head for a while, take a look and see if you can optimise!

As requested I updated the examples and deleted the new ones I'd added. I've not tested these but pretty low risk.

Also updated the readme.

### CODE REVIEW

**Comment by PowerBroker2** [comment]
I made some comments on one of your commits - not sure why the comments don't show up in the merge. If you can't find them, let me know.

**Comment by patfelst** [comment]
Not sure if you saw my latest commit?

**Comment by PowerBroker2** [comment]
Looks good, let me know when you're ready to merge

**Comment by patfelst** [comment]
I'm happy with it now @PowerBroker2, well I'm not planning on doing any more work on it unless you have additional review comments.

I left my own review comment about having added some Serial.printf statements. I went ahead and replaced most of them with Serial.print. There's still one printf in the get_response() function. Not sure if that's bad practise for the smaller lower capability arduinos, you may want to delete it.
https://github.com/PowerBroker2/ELMduino/blob/2ccd9be0a9b918154daf020f5136301d21449305/src/ELMduino.cpp#L2321

**Comment by PowerBroker2** [comment]
Ah, I didn't catch that. I would suggest using the macro `F()` when using `Serial.printf()` (i.e. `Serial.printf(F("0x%02hhX\n"), recChar);). Otherwise it's good to go.

**Comment by patfelst** [comment]
I've tried the F() macro before on printf and it doesn't work. I'll just remove that statement. You rarely see non-printable characters from the ELM327 anyway (one of my scanners showed unprintable characters on one of the init AT commands).

**Comment by patfelst** [comment]
ok I'm done now 😀

**Pull request merged**
